import { Inter, Montserrat, Roboto } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
});

const montSerrat = Montserrat({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Onodwa Siyotula",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html 
      lang="en"
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&family=Roboto:wght@300;400;700&display=swap"
      >
      <body className={`${inter.className} ${montSerrat.className}`}>{children}</body>
    </html>
  );
}
